backend:
  name: git-gateway
  branch: main # ou la branche que tu utilises
  publish_mode: editorial_workflow

media_folder: "images/uploads"  # Dossier pour les médias (dans le répertoire racine)
public_folder: "/images/uploads"  # URL publique pour accéder aux images (correspond au chemin des fichiers sur le site)


collections:
  - name: "recettes-atelier-cuisine"
    label: "RECETTES / ATELIER CUISINE"
    folder: "posts/recettes-atelier-cuisine"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Recettes / atelier cuisine" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }

# Aperçu Netlify CMS avec un Template
site_url: "https://votre-site.netlify.app"  # Votre URL de site
preview_templates:
  - name: "post"
    template: "/layouts/post.njk"
     
    

  - name: "collectivite-rpe"
    label: "LA COLLECTIVITE GRÂCE AU RPE"
    folder: "posts/collectivite-rpe"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "La collectivité grâce au RPE" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image

  - name: "activites-enfant"
    label: "ACTIVITES"
    folder: "posts/activites-enfant"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }   
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Activités" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image

  - name: "selection-produits"
    label: "SELECTION PRODUITS"
    folder: "posts/selection-produits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Sélection produits" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "actu-petite-enfance"
    label: "ACTU PETITE-ENFANCE"
    folder: "posts/actu-petite-enfance"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Actu petite enfance" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image

  - name: "actualites-locales"
    label: "ACTUALITES LOCALES"
    folder: "posts/actualites-locales"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Actualités locales" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image
