backend:
  name: git-gateway
  branch: main # ou la branche que tu utilises

media_folder: "images"  # Dossier pour les médias dans le dépôt (racine du dossier images)
public_folder: "/images" # URL publique pour accéder aux images


site:
  url: "http://localhost:8080" # Remplace par l'URL de ton site en production

collections:
  - name: "recettes-atelier-cuisine"
    label: "RECETTES / ATELIER CUISINE"
    folder: "posts/recettes-atelier-cuisine" # Dossier où les articles seront stockés
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Recettes / atelier cuisine" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }

  - name: "collectivite-rpe"
    label: "LA COLLECTIVITE GRÂCE AU RPE"
    folder: "posts/collectivite-rpe"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "La collectivité grâce au RPE" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }

  - name: "activites-enfant"
    label: "ACTIVITES"
    folder: "posts/activites-enfant"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Activités" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }

  - name: "selection-produits"
    label: "SELECTION PRODUITS"
    folder: "posts/selection-produits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Sélection produits" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }

  - name: "actu-petite-enfance"
    label: "ACTU PETITE-ENFANCE"
    folder: "posts/actu-petite-enfance"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Actu petite enfance" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }

  - name: "actualites-locales"
    label: "ACTUALITES LOCALES"
    folder: "posts/actualites-locales"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Catégorie", name: "category", widget: "string", default: "Actualités locales" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
