backend:
  name: git-gateway
  branch: main # ou la branche que tu utilises
  publish_mode: editorial_workflow

media_folder: "images/uploads"  # Dossier pour les médias (dans le répertoire racine)
public_folder: "/images/uploads"  # URL publique pour accéder aux images (correspond au chemin des fichiers sur le site)

# Aperçu Netlify CMS avec un Template
site_url: "https://test-site-statique-blog-eleventy.netlify.app"  # Votre URL de site
preview_templates:
  - name: "post"
    template: "/layouts/post.njk"


collections:
  - name: "recettes-atelier-cuisine"
    label: "RECETTES / ATELIER CUISINE"
    folder: "posts/recettes-atelier-cuisine"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "hidden", default: "{{now}}" } # Champ Date caché avec la date actuelle par défaut
      - { label: "Catégorie", name: "category", widget: "hidden", default: "RECETTES / ATELIER CUISINE" } # Champ Catégorie caché avec une valeur par défaut
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }


    
  - name: "collectivite-rpe"
    label: "LA COLLECTIVITE GRÂCE AU RPE"
    folder: "posts/collectivite-rpe"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image
      - { label: "Date", name: "date", widget: "hidden", default: "{{now}}" } # Champ Date caché avec la date actuelle par défaut
      - { label: "Catégorie", name: "category", widget: "hidden", default: "LA COLLECTIVITE GRÂCE AU RPE" } # Champ Catégorie caché avec une valeur par défaut
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
     
      

  - name: "activites-enfant"
    label: "ACTIVITES"
    folder: "posts/activites-enfant"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }   
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image
      - { label: "Date", name: "date", widget: "hidden", default: "{{now}}" } # Champ Date caché avec la date actuelle par défaut
      - { label: "Catégorie", name: "category", widget: "hidden", default: "ACTIVITÉS POUR ENFANT" } # Champ Catégorie caché avec une valeur par défaut
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      

  - name: "selection-produits"
    label: "SELECTION PRODUITS"
    folder: "posts/selection-produits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "hidden", default: "{{now}}" } # Champ Date caché avec la date actuelle par défaut
      - { label: "Catégorie", name: "category", widget: "hidden", default: "SELECTION PRODUITS" } # Champ Catégorie caché avec une valeur par défaut
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      
   



  - name: "actu-petite-enfance"
    label: "ACTU PETITE-ENFANCE"
    folder: "posts/actu-petite-enfance"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image
      - { label: "Date", name: "date", widget: "hidden", default: "{{now}}" } # Champ Date caché avec la date actuelle par défaut
      - { label: "Catégorie", name: "category", widget: "hidden", default: "ACTU PETITE-ENFANCE" } # Champ Catégorie caché avec une valeur par défaut
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      

  - name: "actualites-locales"
    label: "ACTUALITES LOCALES"
    folder: "posts/actualites-locales"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "URL", name: "url", widget: "string" }  # Nouveau champ pour l'URL
      - { label: "Image", name: "image", widget: "image" }  # Nouveau champ pour une image
      - { label: "Date", name: "date", widget: "hidden", default: "{{now}}" } # Champ Date caché avec la date actuelle par défaut
      - { label: "Catégorie", name: "category", widget: "hidden", default: "ACTUALITES LOCALES" } # Champ Catégorie caché avec une valeur par défaut
      - { label: "Image vedette", name: "featuredImage", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }

      
      
      
